### ISSUE TITLE
Script Error 

### ISSUE THREAD

**Issue by Joshh1817** [jay-fivem/qb-bong#3]
Hii I have this error on my Console, I'm trying to fix it but I can't. 
![FiveM® by Cfx re - Compostela City RP 3_10_2023 7_17_30 PM](https://user-images.githubusercontent.com/127569909/224453316-66c6b8e0-3c9e-460b-8211-105061519df9.png)

Thanks! I appreciate the help

**Comment by cyneptic** [comment]
I made a pull request which should fix this error, unfortunately i didn't have access to the game to test out my theory so let me know if it didn't work.
